.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "BWA_ALN" "1" "September 2011" "" ""
.
.SH "NAME"
\fBbwa_aln\fR \- Burrows\-Wheeler Aligner
.
.SH "DESCRIPTION"
With the improvement of sequencing techniques, chromatin immunoprecipitation followed by high throughput sequencing (ChIP\-Seq) is getting popular to study genome\-wide protein\-DNA interactions\. To address the lack of powerful ChIP\-Seq analysis method, we present a novel algorithm, named Model\-based Analysis of ChIP\-Seq (MACS), for identifying transcript factor binding sites\. MACS captures the influence of genome complexity to evaluate the significance of enriched ChIP regions, and MACS improves the spatial resolution of binding sites through combining the information of both sequencing tag position and orientation\. MACS can be easily used for ChIP\-Seq data alone, or with control sample with the increase of specificity\.
.
.SH "OPTIONS"
.
.TP
\fB\-\-version\fR, \fBversion\fR \fIboolean\fR
show program\'s version number and exit
.
.TP
\fB\-\-help\fR, \fBhelp\fR \fIboolean\fR
show this help message and exit\.
.
.TP
\fB\-\-treatment\fR, \fBchip\-seq_treatment_files\fR \fIfilepath\fR
ChIP\-seq treatment files\. REQUIRED\. When ELANDMULTIPET is selected, you must provide two files separated by comma
.
.TP
\fB\-\-control\fR, \fBcontrol_files\fR \fIfilepath\fR
Control files\. When ELANDMULTIPET is selected, you must provide two files separated by comma
.
.TP
\fB\-\-name=\fR, \fBname\fR \fIstring\fR
Experiment name, which will be used to generate output file names\. [\fBNA\fR]
.
.TP
\fB\-\-format=\fR, \fBformat\fR \fIstring\fR
Format of tag file\. The default AUTO option will let MACS decide which format the file is\. Please check the definition in 00README file if you choose ELAND/ELANDMULTI/ELANDMULTIPET/ELANDEXPORT/SAM/BAM/BOWTIE\. [\fBAUTO\fR]
.
.TP
\fB\-\-petdist=\fR, \fBbest_distance_between_paired\-end_tags\fR \fIinteger\fR
Best distance between Pair\-End Tags\. Only available when format is \'ELANDMULTIPET\'\. [\fB200\fR]
.
.TP
\fB\-\-gsize=\fR, \fBeffective_genome_size\fR \fIstring\fR
Effective genome size\. It can be 1\.0e+9 or 1000000000, or shortcuts:\'hs\' for human (2\.7e9), \'mm\' for mouse (1\.87e9), \'ce\' for C\. elegans (9e7) and \'dm\' for fruitfly (1\.2e8)\. [\fBhs\fR]
.
.TP
\fB\-\-tsize=\fR, \fBtag_size\fR \fIstring\fR
Tag size\. This will overide the auto detected tag size\.
.
.TP
\fB\-\-bw=\fR, \fBband_width\fR \fIinteger\fR
Band width\. This value is only used while building the shifting model\. [\fB300\fR]
.
.TP
\fB\-\-pvalue=\fR, \fBpvalue_cutoff\fR \fIstring\fR
Pvalue cutoff for peak detection\. [\fB1e\-5\fR]
.
.TP
\fB\-\-mfold\fR, \fBmfold\fR \fIstring\fR
Select the regions within MFOLD range of high\-confidence enrichment ratio against background tobuild model\. The regions must be lower than upperlimit, and higher than the lower limit\. DEFAULT:10,30 [\fB10,30\fR]
.
.TP
\fB\-\-nolambda\fR, \fBnolambda\fR \fIboolean\fR
If True, MACS will use fixed background lambda aslocal lambda for every peak region\. Normally, MACScalculates a dynamic local lambda to reflect the localbias due to potential chromatin structure\. [\fBfalse\fR]
.
.TP
\fB\-\-slocal\fR, \fBslocal\fR \fIinteger\fR
The small nearby region in basepairs to calculatedynamic lambda\. This is used to capture the bias nearthe peak summit region\. Invalid if there is no controldata\. DEFAULT: 1000 [\fB1000\fR]
.
.TP
\fB\-\-llocal\fR, \fBllocal\fR \fIinteger\fR
The large nearby region in basepairs to calculatedynamic lambda\. This is used to capture the surroundbias\. DEFAULT: 10000\. [\fB10000\fR]
.
.TP
\fB\-\-off\-auto\fR, \fBoff\-auto\fR \fIboolean\fR
Whether turn off the auto pair model process\. If notset, when MACS failed to build paired model, it willuse the nomodel settings, the \'\-\-shiftsize\' parameterto shift and extend each tags\. DEFAULT: False [\fBfalse\fR]
.
.TP
\fB\-\-nomodel\fR, \fBnomodel\fR \fIboolean\fR
Whether or not to build the shifting model\. If True,MACS will not build model\. by default it meansshifting size = 100, try to set shiftsize to changeit\. DEFAULT: False [\fBfalse\fR]
.
.TP
\fB\-\-shiftsize\fR, \fBshiftsize\fR \fIinteger\fR
The arbitrary shift size in bp\. When nomodel is true,MACS will use this value as 1/2 of fragment size\.DEFAULT: 100 [\fB100\fR]
.
.TP
\fB\-\-keep\-dup\fR, \fBkeep\-dup\fR \fIstring\fR
It controls the MACS behavior towards duplicate tagsat the exact same location \-\- the same coordinationand the same strand\. The default \'auto\' option makesMACS calculate the maximum tags at the exact samelocation based on binomal distribution using 1e\-5 aspvalue cutoff; and the \'all\' option keeps every tags\.If an integer is given, at most this number of tagswill be kept at the same location\. Default: auto [\fBauto\fR]
.
.TP
\fB\-\-to\-small\fR, \fBto\-small\fR \fIboolean\fR
When set, scale the larger dataset down to the smallerdataset, by default, the smaller dataset will bescaled towards the larger dataset\. DEFAULT: False [\fBfalse\fR]
.
.TP
\fB\-\-wig\fR, \fBwig\fR \fIboolean\fR
Whether or not to save extended fragment pileup atevery WIGEXTEND bps into a wiggle file\. When \-\-single\-profile is on, only one file for the whole genome issaved\. WARNING: this process is time/space consuming!! [\fBfalse\fR]
.
.TP
\fB\-\-bdg\fR, \fBbdg\fR \fIboolean\fR
Whether or not to save extended fragment pileup atevery bp into a bedGraph file\. When it\'s on, \-w,\-\-space and \-\-call\-subpeaks will be ignored\. When\-\-single\-profile is on, only one file for the wholegenome is saved\. WARNING: this process is time/spaceconsuming!! [\fBfalse\fR]
.
.TP
\fB\-\-single\-profile\fR, \fBsingle\-profile\fR \fIboolean\fR
When set, a single wiggle file will be saved fortreatment and input\. Default: False [\fBfalse\fR]
.
.TP
\fB\-\-space\fR, \fBspace\fR \fIinteger\fR
The resoluation for saving wiggle files, by default,MACS will save the raw tag count every 10 bps\. Usableonly with \'\-\-wig\' option\. [\fB10\fR]
.
.TP
\fB\-\-call\-subpeaks\fR, \fBcall\-subpeaks\fR \fIboolean\fR
If set, MACS will invoke Mali Salmon\'s PeakSplittersoft through system call\. If PeakSplitter can\'t befound, an instruction will be shown for downloadingand installing the PeakSplitter package\. \-w optionneeds to be on and \-B should be off to let it work\.DEFAULT: False [\fBfalse\fR]
.
.TP
\fB\-\-verbose\fR, \fBverbose\fR \fIinteger\fR
Set verbose level\. 0: only show critical message, 1:show additional warning message, 2: show processinformation, 3: show debug messages\. DEFAULT:2 [\fB2\fR]
.
.TP
\fB\-\-diag\fR, \fBdiag\fR \fIboolean\fR
Whether or not to produce a diagnosis report\. It\'s upto 9X time consuming\. Please check 00README file fordetail\. DEFAULT: False [\fBfalse\fR]
.
.TP
\fB\-\-fe\-min\fR, \fBfe\-min\fR \fIinteger\fR
For diagnostics, min fold enrichment to consider\.DEFAULT: 0 [\fB0\fR]
.
.TP
\fB\-\-fe\-max\fR, \fBfe\-max\fR \fIstring\fR
For diagnostics, max fold enrichment to consider\.DEFAULT: maximum fold enrichment
.
.TP
\fB\-\-fe\-step\fR, \fBfe\-step\fR \fIinteger\fR
For diagnostics, fold enrichment step\. DEFAULT: 20 [\fB20\fR]

